package com.jjs.zanbi.dao;

import com.jjs.zanbi.model.SendRecord;
import com.jjs.zanbi.model.SendRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int countByExample(SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int deleteByExample(SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int insert(SendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int insertSelective(SendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    List<SendRecord> selectByExample(SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    SendRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") SendRecord record, @Param("example") SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int updateByExample(@Param("record") SendRecord record, @Param("example") SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int updateByPrimaryKeySelective(SendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    int updateByPrimaryKey(SendRecord record);
}