package com.jjs.zanbi.dao;

import com.jjs.zanbi.model.ZbRole;
import com.jjs.zanbi.model.ZbRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ZbRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int countByExample(ZbRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int deleteByExample(ZbRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int insert(ZbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int insertSelective(ZbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    List<ZbRole> selectByExample(ZbRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    ZbRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") ZbRole record, @Param("example") ZbRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int updateByExample(@Param("record") ZbRole record, @Param("example") ZbRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int updateByPrimaryKeySelective(ZbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    int updateByPrimaryKey(ZbRole record);
}