package com.jjs.zanbi.model;

public class Org {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.id
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.org_name
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.org_manager
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    private String orgManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.type
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.id
     *
     * @return the value of org.id
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.id
     *
     * @param id the value for org.id
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.org_name
     *
     * @return the value of org.org_name
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.org_name
     *
     * @param orgName the value for org.org_name
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.org_manager
     *
     * @return the value of org.org_manager
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public String getOrgManager() {
        return orgManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.org_manager
     *
     * @param orgManager the value for org.org_manager
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public void setOrgManager(String orgManager) {
        this.orgManager = orgManager == null ? null : orgManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.type
     *
     * @return the value of org.type
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.type
     *
     * @param type the value for org.type
     *
     * @mbggenerated Fri Jul 29 17:18:43 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}