package com.jjs.zanbi.model;

import java.util.Date;

public class SendRecordDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.sender_id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    private String senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.receiver_id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.send_time
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.remark
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.id
     *
     * @return the value of send_record_detail.id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.id
     *
     * @param id the value for send_record_detail.id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.sender_id
     *
     * @return the value of send_record_detail.sender_id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.sender_id
     *
     * @param senderId the value for send_record_detail.sender_id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.receiver_id
     *
     * @return the value of send_record_detail.receiver_id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.receiver_id
     *
     * @param receiverId the value for send_record_detail.receiver_id
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.send_time
     *
     * @return the value of send_record_detail.send_time
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.send_time
     *
     * @param sendTime the value for send_record_detail.send_time
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.remark
     *
     * @return the value of send_record_detail.remark
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.remark
     *
     * @param remark the value for send_record_detail.remark
     *
     * @mbggenerated Tue Jul 26 22:03:22 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}