package com.jjs.zanbi.model;

import java.util.Date;

public class SendRecordDetail {

    private Worker sender;
    private Worker receiver;

    private SendRecord sendRecord;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.sender_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private Integer senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.receiver_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private Integer receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.zb_count
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private Integer zbCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.send_time
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.remark
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record_detail.send_main_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    private Integer sendMainId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.id
     *
     * @return the value of send_record_detail.id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.id
     *
     * @param id the value for send_record_detail.id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.sender_id
     *
     * @return the value of send_record_detail.sender_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.sender_id
     *
     * @param senderId the value for send_record_detail.sender_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.receiver_id
     *
     * @return the value of send_record_detail.receiver_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.receiver_id
     *
     * @param receiverId the value for send_record_detail.receiver_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.zb_count
     *
     * @return the value of send_record_detail.zb_count
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public Integer getZbCount() {
        return zbCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.zb_count
     *
     * @param zbCount the value for send_record_detail.zb_count
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setZbCount(Integer zbCount) {
        this.zbCount = zbCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.send_time
     *
     * @return the value of send_record_detail.send_time
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.send_time
     *
     * @param sendTime the value for send_record_detail.send_time
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.remark
     *
     * @return the value of send_record_detail.remark
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.remark
     *
     * @param remark the value for send_record_detail.remark
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record_detail.send_main_id
     *
     * @return the value of send_record_detail.send_main_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public Integer getSendMainId() {
        return sendMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record_detail.send_main_id
     *
     * @param sendMainId the value for send_record_detail.send_main_id
     *
     * @mbggenerated Fri Jul 29 13:48:37 CST 2016
     */
    public void setSendMainId(Integer sendMainId) {
        this.sendMainId = sendMainId;
    }


    public Worker getSender() {
        return sender;
    }

    public void setSender(Worker sender) {
        this.sender = sender;
    }

    public Worker getReceiver() {
        return receiver;
    }

    public void setReceiver(Worker receiver) {
        this.receiver = receiver;
    }

    public SendRecord getSendRecord() {
        return sendRecord;
    }

    public void setSendRecord(SendRecord sendRecord) {
        this.sendRecord = sendRecord;
    }
}