package com.jjs.zanbi.model;

import java.util.Date;

public class SendRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record.id
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record.sender_id
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    private Integer senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record.send_time
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record.remark
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_record.sender_ip
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    private String senderIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record.id
     *
     * @return the value of send_record.id
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record.id
     *
     * @param id the value for send_record.id
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record.sender_id
     *
     * @return the value of send_record.sender_id
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record.sender_id
     *
     * @param senderId the value for send_record.sender_id
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record.send_time
     *
     * @return the value of send_record.send_time
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record.send_time
     *
     * @param sendTime the value for send_record.send_time
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record.remark
     *
     * @return the value of send_record.remark
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record.remark
     *
     * @param remark the value for send_record.remark
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_record.sender_ip
     *
     * @return the value of send_record.sender_ip
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public String getSenderIp() {
        return senderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_record.sender_ip
     *
     * @param senderIp the value for send_record.sender_ip
     *
     * @mbggenerated Fri Jul 29 13:51:58 CST 2016
     */
    public void setSenderIp(String senderIp) {
        this.senderIp = senderIp == null ? null : senderIp.trim();
    }
}