package com.jjs.zanbi.model;

import java.util.ArrayList;
import java.util.List;

public class ZbRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public ZbRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andZbCountIsNull() {
            addCriterion("zb_count is null");
            return (Criteria) this;
        }

        public Criteria andZbCountIsNotNull() {
            addCriterion("zb_count is not null");
            return (Criteria) this;
        }

        public Criteria andZbCountEqualTo(Integer value) {
            addCriterion("zb_count =", value, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountNotEqualTo(Integer value) {
            addCriterion("zb_count <>", value, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountGreaterThan(Integer value) {
            addCriterion("zb_count >", value, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("zb_count >=", value, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountLessThan(Integer value) {
            addCriterion("zb_count <", value, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountLessThanOrEqualTo(Integer value) {
            addCriterion("zb_count <=", value, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountIn(List<Integer> values) {
            addCriterion("zb_count in", values, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountNotIn(List<Integer> values) {
            addCriterion("zb_count not in", values, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountBetween(Integer value1, Integer value2) {
            addCriterion("zb_count between", value1, value2, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbCountNotBetween(Integer value1, Integer value2) {
            addCriterion("zb_count not between", value1, value2, "zbCount");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeIsNull() {
            addCriterion("zb_compute_type is null");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeIsNotNull() {
            addCriterion("zb_compute_type is not null");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeEqualTo(String value) {
            addCriterion("zb_compute_type =", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeNotEqualTo(String value) {
            addCriterion("zb_compute_type <>", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeGreaterThan(String value) {
            addCriterion("zb_compute_type >", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("zb_compute_type >=", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeLessThan(String value) {
            addCriterion("zb_compute_type <", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeLessThanOrEqualTo(String value) {
            addCriterion("zb_compute_type <=", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeLike(String value) {
            addCriterion("zb_compute_type like", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeNotLike(String value) {
            addCriterion("zb_compute_type not like", value, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeIn(List<String> values) {
            addCriterion("zb_compute_type in", values, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeNotIn(List<String> values) {
            addCriterion("zb_compute_type not in", values, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeBetween(String value1, String value2) {
            addCriterion("zb_compute_type between", value1, value2, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andZbComputeTypeNotBetween(String value1, String value2) {
            addCriterion("zb_compute_type not between", value1, value2, "zbComputeType");
            return (Criteria) this;
        }

        public Criteria andCalculateIsNull() {
            addCriterion("calculate is null");
            return (Criteria) this;
        }

        public Criteria andCalculateIsNotNull() {
            addCriterion("calculate is not null");
            return (Criteria) this;
        }

        public Criteria andCalculateEqualTo(String value) {
            addCriterion("calculate =", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateNotEqualTo(String value) {
            addCriterion("calculate <>", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateGreaterThan(String value) {
            addCriterion("calculate >", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateGreaterThanOrEqualTo(String value) {
            addCriterion("calculate >=", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateLessThan(String value) {
            addCriterion("calculate <", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateLessThanOrEqualTo(String value) {
            addCriterion("calculate <=", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateLike(String value) {
            addCriterion("calculate like", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateNotLike(String value) {
            addCriterion("calculate not like", value, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateIn(List<String> values) {
            addCriterion("calculate in", values, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateNotIn(List<String> values) {
            addCriterion("calculate not in", values, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateBetween(String value1, String value2) {
            addCriterion("calculate between", value1, value2, "calculate");
            return (Criteria) this;
        }

        public Criteria andCalculateNotBetween(String value1, String value2) {
            addCriterion("calculate not between", value1, value2, "calculate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zb_role
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 27 15:40:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zb_role
     *
     * @mbggenerated Wed Jul 27 15:40:26 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}